# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'rspec'
gem 'timecop'
gem 'pry'
gem 'simplecov', require: false
gem 'simplecov-console', require: false
SimpleCov.formatter = SimpleCov::Formatter::Console
